name: Firebase Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Load Secrets
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "${{ secrets.FIREBASE_SECRETS_PROD }}" > .firebase.env
            echo "${{ secrets.GCP_SA_KEY_PROD }}" > gcp_key.json
            echo "GCP_SA_KEY_FILE=gcp_key.json" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "${{ secrets.FIREBASE_SECRETS_DEV }}" > .firebase.env
            echo "${{ secrets.GCP_SA_KEY_DEV }}" > gcp_key.json
            echo "GCP_SA_KEY_FILE=gcp_key.json" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment."
            exit 1
          fi
        shell: bash

      - name: Export Environment Variables
        run: |
          export $(cat .firebase.env | xargs)
          cat .firebase.env >> $GITHUB_ENV
        shell: bash

      - name: Replace environment variables
        run: npm run env:${{ env.DEPLOY_ENV }}

      - name: Build application
        run: npm run build:${{ env.DEPLOY_ENV }}

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ env.DEPLOY_ENV }} --project ${{ env.FIREBASE_PROJECT_ID }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
