name: Firebase Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Determine Environment
        id: env-setup
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "DEPLOY_ENV=PROD" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "DEPLOY_ENV=DEV" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment."
            exit 1
          fi

      - name: Replace environment variables
        run: npm run env:${{ env.DEPLOY_ENV }}

      - name: Build application
        run: npm run build:${{ env.DEPLOY_ENV }}

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ env.DEPLOY_ENV }} --project ${{ secrets['FIREBASE_PROJECT_ID_' + env.DEPLOY_ENV] }}
        env:
          FIREBASE_APP_ID: ${{ secrets['FIREBASE_APP_ID_' + env.DEPLOY_ENV] }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets['FIREBASE_STORAGE_BUCKET_' + env.DEPLOY_ENV] }}
          FIREBASE_API_KEY: ${{ secrets['FIREBASE_API_KEY_' + env.DEPLOY_ENV] }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets['FIREBASE_AUTH_DOMAIN_' + env.DEPLOY_ENV] }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets['FIREBASE_MESSAGING_SENDER_ID_' + env.DEPLOY_ENV] }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets['FIREBASE_MEASUREMENT_ID_' + env.DEPLOY_ENV] }}
          GCP_SA_KEY: ${{ secrets['GCP_SA_KEY_' + env.DEPLOY_ENV] }}
